name: "Chuyển đổi Gói Tài Nguyên"
description: "Gửi yêu cầu tự động chuyển đổi gói tài nguyên"
title: "[Gói]: "
labels: ["conversion"]
body:
  - type: markdown
    attributes:
      value: |
        Vui lòng đảm bảo bạn đã cung cấp liên kết tải trực tiếp đến gói tài nguyên của mình.  
        Quá trình sẽ thất bại nếu gói không thể được tải xuống.

  - type: input
    id: java-pack-direct-download-url
    attributes:
      label: "Liên kết tải trực tiếp gói Java"
      description: "Vui lòng cung cấp liên kết tải trực tiếp đến gói tài nguyên phiên bản Java cần chuyển đổi."
      placeholder: "ví dụ: https://github.com/Paradisu/ParadisuResourcePack/releases/latest/download/ParadisuResourcePack.zip"
    validations:
      required: true

  - type: input
    id: default-pack-direct-download-url
    attributes:
      label: "Liên kết tải trực tiếp gói mặc định"
      description: "(Tùy chọn) Cung cấp liên kết tải trực tiếp đến gói tài nguyên Java được dùng làm gói mặc định trước khi dùng gói vanilla."
      placeholder: "ví dụ: https://github.com/Paradisu/ParadisuResourcePack/releases/latest/download/ParadisuResourcePack.zip"
    validations:
      required: false

  - type: input
    id: bedrock-merge-pack-direct-download-url
    attributes:
      label: "Liên kết tải trực tiếp gói Bedrock cần gộp"
      description: "(Tùy chọn) Cung cấp liên kết tải trực tiếp đến gói tài nguyên Bedrock sẽ được gộp vào gói đã chuyển đổi."
      placeholder: "ví dụ: https://github.com/Kas-tle/imaginefun-bedrock-rp/releases/download/1.1.3/imaginefun_rp-v1.1.3.mcpack"
    validations:
      required: false

  - type: dropdown
    id: default-assets-version
    attributes:
      label: "Phiên bản tài nguyên mặc định"
      description: "(Tùy chọn) Chọn phiên bản tài nguyên mặc định được dùng cho gói đã chuyển đổi."
      options:
        - "1.13.2"
        - "1.14.4"
        - "1.15.2"
        - "1.16.5"
        - "1.17.1"
        - "1.18.2"
        - "1.19.2"
        - "1.19.3"
        - "1.19.4"
        - "1.20"
        - "1.20.1"
        - "1.21.8"
    validations:
      required: false

  - type: dropdown
    id: block-material
    attributes:
      label: "Chất liệu khối (Block Material)"
      description: |
        Chọn loại chất liệu cho khối được dùng trong script. Nếu không chọn, mặc định là `alpha_test`.  
        Xem thêm tại [Bedrock Wiki](https://wiki.bedrock.dev/blocks/block-materials.html).  
          - `opaque`: không hỗ trợ pixel trong suốt hoặc bán trong suốt, chỉ hiển thị các mặt ngoài  
          - `alpha_test`: hỗ trợ pixel trong suốt, chỉ hiển thị các mặt ngoài  
          - `blend`: hỗ trợ pixel bán trong suốt, chỉ hiển thị các mặt ngoài  
          - `double_sided`: không hỗ trợ pixel trong suốt, hiển thị cả hai mặt
      options:
        - "opaque"
        - "alpha_test"
        - "blend"
        - "double_sided"
    validations:
      required: false

  - type: dropdown
    id: attachable-material
    attributes:
      label: "Chất liệu vật đính kèm (Attachable Material)"
      description: |
        Chọn loại chất liệu được dùng trong script. Nếu không chọn, mặc định là `entity_alphatest_one_sided`.  
        Xem thêm tại [Bedrock Wiki](https://wiki.bedrock.dev/documentation/materials.html).  
          - `entity`: chất liệu mờ đục cơ bản, không hỗ trợ pixel trong suốt  
          - `entity_alphatest`: hỗ trợ pixel trong suốt nhưng không có backface culling (có thể bị lỗi hiển thị khi vật thể mỏng)  
          - `entity_alphablend`: hỗ trợ pixel bán trong suốt và backface culling (nhưng vật thể phía sau có thể hiển thị không nhất quán)  
          - `entity_alphatest_one_sided`: hỗ trợ pixel trong suốt và có backface culling
      options:
        - "entity"
        - "entity_alphatest"
        - "entity_alphablend"
        - "entity_alphatest_one_sided"
        - "entity_emissive_alpha_one_sided"
    validations:
      required: false

  - type: dropdown
    id: archive-scratch
    attributes:
      label: "Lưu trữ tệp tạm (Scratch Files)"
      description: |
        Có muốn lưu trữ các tệp tạm không? Việc này sẽ tạo một tệp ZIP chứa các tệp tạm được dùng trong quá trình chuyển đổi.  
        Nếu không chọn, mặc định là `false`.
      options:
        - "true"
        - "false"

  - type: dropdown
    id: rename-model-files
    attributes:
      label: "Đổi tên tệp mô hình"
      description: |
        Có muốn đổi tên tệp mô hình để rút ngắn đường dẫn không? Nếu không chọn, mặc định là `false`.
      options:
        - "true"
        - "false"

  - type: dropdown
    id: font-conversion
    attributes:
      label: "Chuyển đổi phông chữ"
      description: |
        Bật chuyển đổi phông chữ (có thể gây lỗi). Mặc định là `false`.
      options:
        - "true"
        - "false"

  - type: dropdown
    id: armor-conversion
    attributes:
      label: "Chuyển đổi giáp (Armor)"
      description: |
        Bật chuyển đổi giáp (chỉ dành cho ItemsAdder). Mặc định là `false`.
      options:
        - "true"
        - "false"

  - type: dropdown
    id: meg3-fix
    attributes:
      label: "Sửa lỗi MEG3"
      description: |
        Sửa lỗi mô hình đen trong MEG3. Mặc định là `false`.
      options:
        - "true"
        - "false"

  - type: dropdown
    id: sounds-conversion
    attributes:
      label: "Chuyển đổi âm thanh"
      description: |
        Bật chuyển đổi âm thanh. Mặc định là `false`.
      options:
        - "true"
        - "false"

  - type: dropdown
    id: bow-conversion
    attributes:
      label: "Chuyển đổi cung (Bow)"
      description: |
        Bật chuyển đổi cung. Mặc định là `false`.
      options:
        - "true"
        - "false"

  - type: dropdown
    id: shield-conversion
    attributes:
      label: "Chuyển đổi khiên (Shield)"
      description: |
        Bật chuyển đổi khiên. Mặc định là `false`. **Chưa sẵn sàng để sử dụng**
      options:
        - "true"
        - "false"

  - type: dropdown
    id: block-conversion
    attributes:
      label: "Chuyển đổi khối (Block)"
      description: |
        Bật chuyển đổi khối. Mặc định là `false`.
      options:
        - "true"
        - "false"

  - type: checkboxes
    id: terms
    attributes:
      label: "Quy tắc ứng xử (Code of Conduct)"
      description: |
        Khi gửi yêu cầu này, bạn đồng ý tuân thủ [Quy tắc Ứng xử](https://github.com/Kas-tle/java2bedrock.sh/blob/main/CODE_OF_CONDUCT.md).  
        Đồng thời, bạn xác nhận rằng bạn sở hữu hoặc có quyền sử dụng tất cả nội dung đã liên kết trong biểu mẫu này.
      options:
        - label: "Tôi đồng ý tuân thủ Quy tắc Ứng xử của dự án này và có quyền sử dụng tất cả tài nguyên đã liên kết."
          required: true
