name: Yêu cầu Chuyển đổi Gói tài nguyên
description: Gửi yêu cầu chuyển đổi gói tài nguyên tự động
title: "[Gói]: "
labels: ["conversion"]
body:
  - type: markdown
    attributes:
      value: |
        Vui lòng đảm bảo bạn cung cấp một liên kết tải trực tiếp đến gói của bạn. Quy trình sẽ thất bại nếu không thể tải gói về.
  - type: input
    id: java-pack-direct-download-url
    attributes:
      label: URL Tải trực tiếp Gói Java
      description: Vui lòng cung cấp một liên kết trực tiếp đến gói tài nguyên Java Edition cần chuyển đổi.
      placeholder: VD: https://github.com/Paradisu/ParadisuResourcePack/releases/latest/download/ParadisuResourcePack.zip
    validations:
      required: true
  - type: input
    id: default-pack-direct-download-url
    attributes:
      label: URL Tải Gói Mặc định (Tùy chọn)
      description: Tùy chọn, cung cấp liên kết trực tiếp đến một gói tài nguyên Java khác để sử dụng làm texture mặc định (sẽ được ưu tiên hơn gói vanilla mặc định).
      placeholder: VD: https://github.com/Paradisu/ParadisuResourcePack/releases/latest/download/ParadisuResourcePack.zip
    validations:
      required: false
  - type: input
    id: bedrock-merge-pack-direct-download-url
    attributes:
      label: URL Gói Bedrock để Hợp nhất (Tùy chọn)
      description: Tùy chọn, cung cấp liên kết trực tiếp đến một gói tài nguyên Bedrock Edition để hợp nhất vào gói đã chuyển đổi.
      placeholder: VD: https://github.com/Kas-tle/imaginefun-bedrock-rp/releases/download/1.1.3/imaginefun_rp-v1.1.3.mcpack
    validations:
      required: false
  - type: dropdown
    id: default-assets-version
    attributes:
      label: Phiên bản Tài nguyên Mặc định
      description: Tùy chọn, chọn phiên bản tài nguyên mặc định để sử dụng cho gói chuyển đổi.
      options:
        - 1.16.5
        - 1.17.1
        - 1.18.2
        - 1.19.4
        - 1.20.1
        - 1.20.4
        - 1.20.6
        - 1.21
        - 1.21.1
        - 1.21.4
        - 1.21.8
        - 1.21.9
        - 1.21.10
    validations:
      required: false

  - type: dropdown
    id: block-material
    attributes:
      label: Vật liệu Khối (Block Material)
      description: |
        Vui lòng chọn một vật liệu khối để sử dụng. Nếu không chọn, `alpha_test` sẽ được sử dụng.
        Xem thêm tại [Bedrock Wiki](https://wiki.bedrock.dev/blocks/block-materials.html).
          - `opaque`: không hỗ trợ pixel trong suốt hoặc mờ, chỉ render mặt ngoài
          - `alpha_test`: hỗ trợ pixel trong suốt, chỉ render mặt ngoài
          - `blend`: hỗ trợ pixel mờ, chỉ render mặt ngoài
          - `double_sided`: không hỗ trợ pixel trong suốt hoặc mờ, nhưng render cả mặt trong và mặt ngoài
      options:
        - opaque
        - alpha_test
        - blend
        - double_sided
    validations:
      required: false
  - type: dropdown
    id: attachable-material
    attributes:
      label: Vật liệu Vật thể đính kèm (Attachable Material)
      description: |
        Vui lòng chọn một vật liệu attachable để sử dụng. Nếu không chọn, `entity_alphatest_one_sided` sẽ được sử dụng.
        Xem thêm tại [Bedrock Wiki](https://wiki.bedrock.dev/documentation/materials.html).
          - `entity`: vật liệu đục cơ bản, không hỗ trợ pixel trong suốt hoặc mờ
          - `entity_alphatest`: hỗ trợ pixel trong suốt nhưng có thể bị lỗi z-fighting
          - `entity_alphablend`: hỗ trợ pixel mờ
          - `entity_alphatest_one_sided`: hỗ trợ pixel trong suốt và render một mặt
      options:
        - entity
        - entity_alphatest
        - entity_alphablend
        - entity_alphatest_one_sided
        - entity_emissive_alpha_one_sided
    validations:
      required: false
  - type: dropdown
    id: archive-scratch
    attributes:
      label: Lưu trữ File nháp (Scratch Files)
      description: |
        Có nên lưu lại các file nháp không? Thao tác này sẽ tạo một file zip chứa các file tạm được sử dụng trong quá trình chuyển đổi. Mặc định là `false`.
      options:
        - 'true'
        - 'false'
  - type: dropdown
    id: rename-model-files
    attributes:
      label: Đổi tên file Model
      description: |
        Có nên đổi tên file model để giảm độ dài đường dẫn không? Mặc định là `false`.
      options:
        - 'true'
        - 'false'
  - type: dropdown
    id: font-conversion
    attributes:
      label: Chuyển đổi Font chữ
      description: |
        Bật tính năng chuyển đổi font (Có thể gây lỗi). Mặc định là `false`.
      options:
        - 'true'
        - 'false'
  - type: dropdown
    id: armor-conversion
    attributes:
      label: Chuyển đổi Giáp
      description: |
        Bật tính năng chuyển đổi giáp (Chỉ hỗ trợ ItemsAdder). Mặc định là `false`.
      options:
        - 'true'
        - 'false'
  - type: dropdown
    id: meg3-fix
    attributes:
      label: Sửa lỗi Meg3
      description: |
        Sửa lỗi model bị đen cho MEG3. Mặc định là `false`.
      options:
        - 'true'
        - 'false'
  - type: dropdown
    id: sounds-conversion
    attributes:
      label: Chuyển đổi Âm thanh
      description: |
        Bật tính năng chuyển đổi âm thanh. Mặc định là `false`.
      options:
        - 'true'
        - 'false'
  - type: dropdown
    id: bow-conversion
    attributes:
      label: Chuyển đổi Cung
      description: |
        Bật tính năng chuyển đổi cung. Mặc định là `false`.
      options:
        - 'true'
        - 'false'
  - type: dropdown
    id: shield-conversion
    attributes:
      label: Chuyển đổi Khiên
      description: |
        Bật tính năng chuyển đổi khiên. Mặc định là `false`. **Chưa sẵn sàng để sử dụng**
      options:
        - 'true'
        - 'false'
  - type: dropdown
    id: block-conversion
    attributes:
      label: Chuyển đổi Khối
      description: |
        Bật tính năng chuyển đổi khối. Mặc định là `false`.
      options:
        - 'true'
        - 'false'
  - type: checkboxes
    id: terms
    attributes:
      label: Quy tắc Ứng xử
      description: |
        Bằng việc gửi issue này, bạn đồng ý tuân theo [Quy tắc ứng xử](https://github.com/Kas-tle/java2bedrock.sh/blob/main/CODE_OF_CONDUCT.md) của chúng tôi.
        Bạn cũng đồng ý rằng bạn sở hữu hoặc có quyền sử dụng tất cả nội dung bạn đã liên kết trong biểu mẫu này.
      options:
        - label: Tôi đồng ý tuân theo Quy tắc ứng xử của dự án. Tôi có quyền sử dụng tất cả các tài sản mà tôi đã liên kết trong biểu mẫu này.
          required: true
